name = "ObservablePlots"
uuid = "828d9ff0-206c-6161-646e-6576656f7244"
license = "MIT"
authors = ["Fons van der Plas <fons@plutojl.org>"]
version = "0.1.0"

[deps]
AbstractPlutoDingetjes = "6e696c72-6542-2067-7265-42206c756150"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"

[compat]
AbstractPlutoDingetjes = "1.3.2"
HypertextLiteral = "0.9.5"
julia = "1.10"

[extras]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Markdown", "Test"]
